window.ACM_SEED = {
  "version": 1,
  "generated_for": "2026-09-25",
  "demo_logins": {
    "admin": {
      "username": "demo",
      "password": "demo"
    },
    "caretaker": {
      "username": "caretaker",
      "password": "demo"
    }
  },
  "rfid_examples": [
    "31010",
    "31012",
    "982000000031010"
  ],
  "users": [
    {
      "user_id": 1,
      "username": "demo",
      "password": "demo",
      "email": "demo@example.com",
      "role": "admin",
      "full_name": "Demo Admin",
      "active": 1
    },
    {
      "user_id": 2,
      "username": "caretaker",
      "password": "demo",
      "email": "care@example.com",
      "role": "caretaker",
      "full_name": "Casey Caretaker",
      "active": 1
    },
    {
      "user_id": 3,
      "username": "research",
      "password": "demo",
      "email": "research@example.com",
      "role": "research",
      "full_name": "Riley Research",
      "active": 1
    }
  ],
  "addresses": [
    {
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "address_id": 2,
      "room_id": 1,
      "cage_address": "B",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "address_id": 4,
      "room_id": 2,
      "cage_address": "B",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "address_id": 5,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "address_id": 6,
      "room_id": 3,
      "cage_address": "B",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "address_id": 7,
      "room_id": 4,
      "cage_address": "A",
      "room_name": "Research",
      "room_lighting": "Top"
    },
    {
      "address_id": 8,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top"
    }
  ],
  "suppliers": [
    {
      "supplier_id": 1,
      "supplier_name": "Demo Supplier",
      "contact_info": "demo@example.com"
    }
  ],
  "distributors": [
    {
      "distributor_id": 1,
      "distributor_name": "North Lab Partners"
    }
  ],
  "ferrets": [
    {
      "id": 1,
      "Ferret_QR005_id": 1,
      "name": "Cedar",
      "ferret_name": "Cedar",
      "animal_id": 10001,
      "sex": "male",
      "birth_date": "2022-09-26",
      "weight": 1480,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "1",
      "death_date": "2026-08-16",
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 8,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-10-15",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": "Old Age",
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 2,
      "Ferret_QR005_id": 2,
      "name": "Pine",
      "ferret_name": "Pine",
      "animal_id": 10002,
      "sex": "male",
      "birth_date": "2023-06-28",
      "weight": 1420,
      "color": "cinnamon",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 5,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-10-20",
      "eight_hour_light": 1,
      "light_state_since": "2026-07-27",
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 1,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 3,
      "Ferret_QR005_id": 3,
      "name": "Willow",
      "ferret_name": "Willow",
      "animal_id": 10003,
      "sex": "female",
      "birth_date": "2022-09-26",
      "weight": 820,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 6,
      "room_id": 3,
      "cage_address": "B",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2023-09-26",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 4,
      "Ferret_QR005_id": 4,
      "name": "Hazel",
      "ferret_name": "Hazel",
      "animal_id": 10004,
      "sex": "female",
      "birth_date": "2023-08-27",
      "weight": 790,
      "color": "champagne",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 6,
      "room_id": 3,
      "cage_address": "B",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-10-10",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": "estrus",
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 5,
      "Ferret_QR005_id": 5,
      "name": "Ivy",
      "ferret_name": "Ivy",
      "animal_id": 10005,
      "sex": "female",
      "birth_date": "2023-11-05",
      "weight": 810,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 5,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2024-11-04",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": "mated",
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 6,
      "Ferret_QR005_id": 6,
      "name": "Maple",
      "ferret_name": "Maple",
      "animal_id": 10006,
      "sex": "female",
      "birth_date": "2024-03-12",
      "weight": 800,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 3,
      "father_id": 1,
      "mother_name": "Willow",
      "father_name": "Cedar",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-09-05",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 1,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 7,
      "Ferret_QR005_id": 7,
      "name": "Birch",
      "ferret_name": "Birch",
      "animal_id": 10007,
      "sex": "male",
      "birth_date": "2024-03-12",
      "weight": 1380,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 5,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": 3,
      "father_id": 1,
      "mother_name": "Willow",
      "father_name": "Cedar",
      "litter_id": "HIST-W1",
      "litter_date": "2024-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2025-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 8,
      "Ferret_QR005_id": 8,
      "name": "Ash",
      "ferret_name": "Ash",
      "animal_id": 10008,
      "sex": "male",
      "birth_date": "2024-05-20",
      "weight": 1350,
      "color": "cinnamon",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": "offsite",
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 5,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom",
      "mother_id": 4,
      "father_id": 2,
      "mother_name": "Hazel",
      "father_name": "Pine",
      "litter_id": "HIST-H1",
      "litter_date": "2024-05-20",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2025-05-20",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 9,
      "Ferret_QR005_id": 9,
      "name": "Wren",
      "ferret_name": "Wren",
      "animal_id": 10009,
      "sex": "female",
      "birth_date": "2024-05-20",
      "weight": 780,
      "color": "cinnamon",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 4,
      "father_id": 2,
      "mother_name": "Hazel",
      "father_name": "Pine",
      "litter_id": "HIST-H1",
      "litter_date": "2024-05-20",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-09-30",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": "littered",
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 10,
      "Ferret_QR005_id": 10,
      "name": "Nova",
      "ferret_name": "Nova",
      "animal_id": 10010,
      "sex": "female",
      "birth_date": "2024-07-01",
      "weight": 795,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 5,
      "father_id": 1,
      "mother_name": "Ivy",
      "father_name": "Cedar",
      "litter_id": "HIST-I1",
      "litter_date": "2024-07-01",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-09-30",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": "littered",
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 11,
      "Ferret_QR005_id": 11,
      "name": "Piper",
      "ferret_name": "Piper",
      "animal_id": 10011,
      "sex": "female",
      "birth_date": "2024-07-01",
      "weight": 805,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 2,
      "room_id": 1,
      "cage_address": "B",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 5,
      "father_id": 1,
      "mother_name": "Ivy",
      "father_name": "Cedar",
      "litter_id": "HIST-I1",
      "litter_date": "2024-07-01",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-09-30",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": "littered",
      "needs_bath": 1,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 12,
      "Ferret_QR005_id": 12,
      "name": "Reed",
      "ferret_name": "Reed",
      "animal_id": 10012,
      "sex": "male",
      "birth_date": "2024-07-01",
      "weight": 1320,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 1,
      "research_cohort": "baseline",
      "archived": 0,
      "address_id": 7,
      "room_id": 4,
      "cage_address": "A",
      "room_name": "Research",
      "room_lighting": "Top",
      "mother_id": 5,
      "father_id": 1,
      "mother_name": "Ivy",
      "father_name": "Cedar",
      "litter_id": "HIST-I1",
      "litter_date": "2024-07-01",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2025-07-01",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 13,
      "Ferret_QR005_id": 13,
      "name": "Lark",
      "ferret_name": "Lark",
      "animal_id": 10013,
      "sex": "female",
      "birth_date": "2025-08-21",
      "weight": 760,
      "color": "panda",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 4,
      "room_id": 2,
      "cage_address": "B",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 3,
      "father_id": 2,
      "mother_name": "Willow",
      "father_name": "Pine",
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-09-30",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 14,
      "Ferret_QR005_id": 14,
      "name": "Quill",
      "ferret_name": "Quill",
      "animal_id": 10014,
      "sex": "male",
      "birth_date": "2025-09-10",
      "weight": 1280,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 4,
      "room_id": 2,
      "cage_address": "B",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 4,
      "father_id": 1,
      "mother_name": "Hazel",
      "father_name": "Cedar",
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-09-10",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 15,
      "Ferret_QR005_id": 15,
      "name": "Sable",
      "ferret_name": "Sable",
      "animal_id": 10015,
      "sex": "female",
      "birth_date": "2025-05-13",
      "weight": 770,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 1,
      "distribution_date": "2026-09-05",
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 8,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top",
      "mother_id": null,
      "father_id": null,
      "mother_name": null,
      "father_name": null,
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Sourced",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-05-13",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 16,
      "Ferret_QR005_id": 16,
      "name": "Fern",
      "ferret_name": "Fern",
      "animal_id": 10016,
      "sex": "female",
      "birth_date": "2025-01-13",
      "weight": 740,
      "color": "champagne",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "1",
      "death_date": "2026-09-22",
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 8,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top",
      "mother_id": 3,
      "father_id": 2,
      "mother_name": "Willow",
      "father_name": "Pine",
      "litter_id": null,
      "litter_date": null,
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2026-01-13",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": "Unknown",
      "death_female_status": "mated",
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 17,
      "Ferret_QR005_id": 17,
      "name": "Kit-Cedarling",
      "ferret_name": "Kit-Cedarling",
      "animal_id": 10017,
      "sex": "male",
      "birth_date": "2026-08-14",
      "weight": 446,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": true,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 18,
      "Ferret_QR005_id": 18,
      "name": "Kit-Moss",
      "ferret_name": "Kit-Moss",
      "animal_id": 10018,
      "sex": "female",
      "birth_date": "2026-08-14",
      "weight": 454,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": false,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 19,
      "Ferret_QR005_id": 19,
      "name": "Kit-Pebble",
      "ferret_name": "Kit-Pebble",
      "animal_id": 10019,
      "sex": "male",
      "birth_date": "2026-08-14",
      "weight": 462,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": false,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 20,
      "Ferret_QR005_id": 20,
      "name": "Kit-Daisy",
      "ferret_name": "Kit-Daisy",
      "animal_id": 10020,
      "sex": "female",
      "birth_date": "2026-08-14",
      "weight": 470,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": false,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 21,
      "Ferret_QR005_id": 21,
      "name": "Kit-Bramble",
      "ferret_name": "Kit-Bramble",
      "animal_id": 10021,
      "sex": "male",
      "birth_date": "2026-08-14",
      "weight": 478,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": false,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 22,
      "Ferret_QR005_id": 22,
      "name": "Kit-Nettle",
      "ferret_name": "Kit-Nettle",
      "animal_id": 10022,
      "sex": "female",
      "birth_date": "2026-08-14",
      "weight": 486,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 1,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top",
      "mother_id": 9,
      "father_id": 7,
      "mother_name": "Wren",
      "father_name": "Birch",
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-08-14",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": false,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 23,
      "Ferret_QR005_id": 23,
      "name": "Rowan",
      "ferret_name": "Rowan",
      "animal_id": 10023,
      "sex": "male",
      "birth_date": "2026-03-12",
      "weight": 980,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 24,
      "Ferret_QR005_id": 24,
      "name": "Thistle",
      "ferret_name": "Thistle",
      "animal_id": 10024,
      "sex": "female",
      "birth_date": "2026-03-12",
      "weight": 980,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 25,
      "Ferret_QR005_id": 25,
      "name": "Alder",
      "ferret_name": "Alder",
      "animal_id": 10025,
      "sex": "male",
      "birth_date": "2026-03-12",
      "weight": 980,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 26,
      "Ferret_QR005_id": 26,
      "name": "Briar",
      "ferret_name": "Briar",
      "animal_id": 10026,
      "sex": "female",
      "birth_date": "2026-03-12",
      "weight": 980,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 27,
      "Ferret_QR005_id": 27,
      "name": "Holly",
      "ferret_name": "Holly",
      "animal_id": 10027,
      "sex": "male",
      "birth_date": "2026-03-12",
      "weight": 980,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "0",
      "death_date": null,
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 3,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": null,
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    },
    {
      "id": 28,
      "Ferret_QR005_id": 28,
      "name": "Yarrow",
      "ferret_name": "Yarrow",
      "animal_id": 10028,
      "sex": "female",
      "birth_date": "2026-03-12",
      "weight": 40,
      "color": "sable",
      "description": "Demo animal \u2014 fictional.",
      "photo_url": null,
      "dead": "1",
      "death_date": "2026-05-07",
      "distributed": 0,
      "distribution_date": null,
      "distribution_tag": null,
      "in_research": 0,
      "research_cohort": null,
      "archived": 0,
      "address_id": 8,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top",
      "mother_id": 6,
      "father_id": 7,
      "mother_name": "Maple",
      "father_name": "Birch",
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "acquisition_class": "Littered",
      "acquisition_by": "Demo Colony",
      "next_rabies_vaccine_due": "2027-03-12",
      "eight_hour_light": 0,
      "light_state_since": null,
      "female_status": null,
      "needs_bath": 0,
      "needs_nail_trim": 0,
      "cause_of_death": "Unknown",
      "death_female_status": null,
      "supplier_name": "Demo Supplier",
      "created_by": "demo"
    }
  ],
  "rfid_assignments": [
    {
      "rfid_id": 1,
      "rfid": "982000000031001",
      "ferret_id": 1,
      "assigned_date": "2022-09-26",
      "unassigned_date": "2026-08-16",
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 2,
      "rfid": "982000000031002",
      "ferret_id": 2,
      "assigned_date": "2023-06-28",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 3,
      "rfid": "982000000031003",
      "ferret_id": 3,
      "assigned_date": "2022-09-26",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 4,
      "rfid": "982000000031004",
      "ferret_id": 4,
      "assigned_date": "2023-08-27",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 5,
      "rfid": "982000000031005",
      "ferret_id": 5,
      "assigned_date": "2023-11-05",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 6,
      "rfid": "982000000031006",
      "ferret_id": 6,
      "assigned_date": "2024-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 7,
      "rfid": "982000000031007",
      "ferret_id": 7,
      "assigned_date": "2024-03-12",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 8,
      "rfid": "982000000031008",
      "ferret_id": 8,
      "assigned_date": "2024-05-20",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 9,
      "rfid": "982000000031009",
      "ferret_id": 9,
      "assigned_date": "2024-05-20",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 10,
      "rfid": "982000000031010",
      "ferret_id": 10,
      "assigned_date": "2024-07-01",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 11,
      "rfid": "982000000031011",
      "ferret_id": 11,
      "assigned_date": "2024-07-01",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 12,
      "rfid": "982000000031012",
      "ferret_id": 12,
      "assigned_date": "2024-07-01",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 13,
      "rfid": "982000000031013",
      "ferret_id": 13,
      "assigned_date": "2025-08-21",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 14,
      "rfid": "982000000031014",
      "ferret_id": 14,
      "assigned_date": "2025-09-10",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 15,
      "rfid": "982000000031015",
      "ferret_id": 15,
      "assigned_date": "2025-05-13",
      "unassigned_date": null,
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 16,
      "rfid": "982000000031016",
      "ferret_id": 16,
      "assigned_date": "2025-01-13",
      "unassigned_date": "2026-09-22",
      "reason": "intake",
      "notes": null
    },
    {
      "rfid_id": 17,
      "rfid": "982000000031017",
      "ferret_id": 17,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 18,
      "rfid": "982000000031018",
      "ferret_id": 18,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 19,
      "rfid": "982000000031019",
      "ferret_id": 19,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 20,
      "rfid": "982000000031020",
      "ferret_id": 20,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 21,
      "rfid": "982000000031021",
      "ferret_id": 21,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 22,
      "rfid": "982000000031022",
      "ferret_id": 22,
      "assigned_date": "2026-08-14",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 23,
      "rfid": "982000000031023",
      "ferret_id": 23,
      "assigned_date": "2026-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 24,
      "rfid": "982000000031024",
      "ferret_id": 24,
      "assigned_date": "2026-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 25,
      "rfid": "982000000031025",
      "ferret_id": 25,
      "assigned_date": "2026-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 26,
      "rfid": "982000000031026",
      "ferret_id": 26,
      "assigned_date": "2026-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 27,
      "rfid": "982000000031027",
      "ferret_id": 27,
      "assigned_date": "2026-03-12",
      "unassigned_date": null,
      "reason": "wean chip",
      "notes": null
    },
    {
      "rfid_id": 28,
      "rfid": "982000000031028",
      "ferret_id": 28,
      "assigned_date": "2026-03-12",
      "unassigned_date": "2026-05-07",
      "reason": "wean chip",
      "notes": null
    }
  ],
  "health_events": [
    {
      "health_event_id": 1,
      "ferret_id": 6,
      "event_type": "weight",
      "weight": 760,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 2,
      "ferret_id": 6,
      "event_type": "weight",
      "weight": 785,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 3,
      "ferret_id": 6,
      "event_type": "weight",
      "weight": 800,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 4,
      "ferret_id": 7,
      "event_type": "weight",
      "weight": 1340,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 5,
      "ferret_id": 7,
      "event_type": "weight",
      "weight": 1365,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 6,
      "ferret_id": 7,
      "event_type": "weight",
      "weight": 1380,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 7,
      "ferret_id": 9,
      "event_type": "weight",
      "weight": 740,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 8,
      "ferret_id": 9,
      "event_type": "weight",
      "weight": 765,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 9,
      "ferret_id": 9,
      "event_type": "weight",
      "weight": 780,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 10,
      "ferret_id": 10,
      "event_type": "weight",
      "weight": 755,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 11,
      "ferret_id": 10,
      "event_type": "weight",
      "weight": 780,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 12,
      "ferret_id": 10,
      "event_type": "weight",
      "weight": 795,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 13,
      "ferret_id": 12,
      "event_type": "weight",
      "weight": 1280,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 14,
      "ferret_id": 12,
      "event_type": "weight",
      "weight": 1305,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 15,
      "ferret_id": 12,
      "event_type": "weight",
      "weight": 1320,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 16,
      "ferret_id": 23,
      "event_type": "weight",
      "weight": 940,
      "event_date": "2026-07-27",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 17,
      "ferret_id": 23,
      "event_type": "weight",
      "weight": 965,
      "event_date": "2026-08-26",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 18,
      "ferret_id": 23,
      "event_type": "weight",
      "weight": 980,
      "event_date": "2026-09-18",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 19,
      "ferret_id": 6,
      "event_type": "bath",
      "weight": null,
      "event_date": "2026-09-21",
      "notes": "Demo bath",
      "recorded_by": "demo"
    },
    {
      "health_event_id": 20,
      "ferret_id": 2,
      "event_type": "nail_trim",
      "weight": null,
      "event_date": "2026-09-15",
      "notes": null,
      "recorded_by": "demo"
    },
    {
      "health_event_id": 21,
      "ferret_id": 11,
      "event_type": "bath",
      "weight": null,
      "event_date": "2026-09-05",
      "notes": null,
      "recorded_by": "demo"
    }
  ],
  "vaccinations": [
    {
      "vaccination_id": 1,
      "ferret_id": 2,
      "vaccine_type": "rabies",
      "event_date": "2025-10-20",
      "expiration_date": "2026-10-20",
      "next_due": "2026-10-20",
      "administered_by": "Riley Research",
      "notes": null
    },
    {
      "vaccination_id": 2,
      "ferret_id": 6,
      "vaccine_type": "rabies",
      "event_date": "2026-09-05",
      "expiration_date": "2027-09-05",
      "next_due": "2027-09-05",
      "administered_by": "Riley Research",
      "notes": null
    },
    {
      "vaccination_id": 3,
      "ferret_id": 4,
      "vaccine_type": "rabies",
      "event_date": "2025-10-10",
      "expiration_date": "2026-10-10",
      "next_due": "2026-10-10",
      "administered_by": "Riley Research",
      "notes": "Due soon"
    }
  ],
  "litters": [
    {
      "litter_log_id": 1,
      "litter_id": "LIT0001",
      "litter_date": "2026-09-23",
      "Ferret_QR005_id": 10,
      "jill_id": 10,
      "jill_name": "Nova",
      "father": "Ash",
      "father_id": 8,
      "mother": "Nova",
      "kit_count": 7,
      "stillborn": 1,
      "infant_deaths": 0,
      "surviving_litter_count": 6,
      "individuals_created": 0,
      "last_weight_grams": 270,
      "last_weigh_date": "2026-09-24",
      "previous_weight_grams": 210,
      "previous_weigh_date": "2026-09-23",
      "anomalies_and_notes": "Brand-new nursing litter (demo).",
      "kits_separated_at": null,
      "created_by": "demo",
      "start_kit_on_feed": "2026-10-14"
    },
    {
      "litter_log_id": 2,
      "litter_id": "LIT0002",
      "litter_date": "2026-09-04",
      "Ferret_QR005_id": 11,
      "jill_id": 11,
      "jill_name": "Piper",
      "father": "Ash",
      "father_id": 8,
      "mother": "Piper",
      "kit_count": 8,
      "stillborn": 0,
      "infant_deaths": 1,
      "surviving_litter_count": 7,
      "individuals_created": 0,
      "last_weight_grams": 320,
      "last_weigh_date": "2026-09-23",
      "previous_weight_grams": 250,
      "previous_weigh_date": "2026-09-16",
      "anomalies_and_notes": "Soft-food start window (demo).",
      "kits_separated_at": null,
      "created_by": "demo",
      "start_kit_on_feed": "2026-09-25"
    },
    {
      "litter_log_id": 3,
      "litter_id": "LIT0003",
      "litter_date": "2026-08-14",
      "Ferret_QR005_id": 9,
      "jill_id": 9,
      "jill_name": "Wren",
      "father": "Birch",
      "father_id": 7,
      "mother": "Wren",
      "kit_count": 6,
      "stillborn": 0,
      "infant_deaths": 0,
      "surviving_litter_count": 6,
      "individuals_created": 6,
      "last_weight_grams": 1800,
      "last_weigh_date": "2026-09-22",
      "previous_weight_grams": 1500,
      "previous_weigh_date": "2026-09-15",
      "anomalies_and_notes": "Wean / chip window (demo).",
      "kits_separated_at": null,
      "created_by": "demo",
      "start_kit_on_feed": "2026-09-04"
    },
    {
      "litter_log_id": 4,
      "litter_id": "LIT0004",
      "litter_date": "2026-03-12",
      "Ferret_QR005_id": 6,
      "jill_id": 6,
      "jill_name": "Maple",
      "father": "Birch",
      "father_id": 7,
      "mother": "Maple",
      "kit_count": 8,
      "stillborn": 1,
      "infant_deaths": 1,
      "surviving_litter_count": 6,
      "individuals_created": 6,
      "last_weight_grams": null,
      "last_weigh_date": null,
      "previous_weight_grams": null,
      "previous_weigh_date": null,
      "anomalies_and_notes": "Scored 6-month survival. Parents are full siblings \u2014 kits have elevated CoI.",
      "kits_separated_at": "2026-04-23",
      "created_by": "demo",
      "start_kit_on_feed": "2026-04-02"
    }
  ],
  "litter_care_events": [
    {
      "care_event_id": 1,
      "litter_log_id": 1,
      "event_type": "weight",
      "event_date": "2026-09-24",
      "weight_grams": 270,
      "kit_count": 6,
      "notes": "Demo weigh",
      "recorded_by": "demo"
    },
    {
      "care_event_id": 2,
      "litter_log_id": 2,
      "event_type": "weight",
      "event_date": "2026-09-23",
      "weight_grams": 320,
      "kit_count": 7,
      "notes": "Demo weigh",
      "recorded_by": "demo"
    },
    {
      "care_event_id": 3,
      "litter_log_id": 3,
      "event_type": "weight",
      "event_date": "2026-09-22",
      "weight_grams": 1800,
      "kit_count": 6,
      "notes": "Demo weigh",
      "recorded_by": "demo"
    }
  ],
  "kit_deaths": [
    {
      "kit_death_id": 1,
      "litter_log_id": 2,
      "death_date": "2026-09-09",
      "cause_category": "failure_to_thrive",
      "notes": "Pre-ID kit death (demo).",
      "recorded_by": "demo",
      "litter_id": "LIT0002",
      "jill_name": "Piper"
    },
    {
      "kit_death_id": 2,
      "litter_log_id": 4,
      "death_date": "2026-03-22",
      "cause_category": "crushed",
      "notes": "Pre-ID kit death (demo).",
      "recorded_by": "demo",
      "litter_id": "LIT0004",
      "jill_name": "Maple"
    }
  ],
  "reproductive_events": [
    {
      "repro_id": 1,
      "ferret_id": 10,
      "event_type": "mated",
      "event_date": "2026-08-12",
      "partner_id": 8,
      "notes": "Demo mating",
      "recorded_by": "demo"
    },
    {
      "repro_id": 2,
      "ferret_id": 10,
      "event_type": "littered",
      "event_date": "2026-09-23",
      "partner_id": 8,
      "notes": "LIT0001",
      "recorded_by": "demo"
    },
    {
      "repro_id": 3,
      "ferret_id": 11,
      "event_type": "mated",
      "event_date": "2026-07-24",
      "partner_id": 8,
      "notes": "Demo mating",
      "recorded_by": "demo"
    },
    {
      "repro_id": 4,
      "ferret_id": 11,
      "event_type": "littered",
      "event_date": "2026-09-04",
      "partner_id": 8,
      "notes": "LIT0002",
      "recorded_by": "demo"
    },
    {
      "repro_id": 5,
      "ferret_id": 9,
      "event_type": "mated",
      "event_date": "2026-07-03",
      "partner_id": 7,
      "notes": "Demo mating",
      "recorded_by": "demo"
    },
    {
      "repro_id": 6,
      "ferret_id": 9,
      "event_type": "littered",
      "event_date": "2026-08-14",
      "partner_id": 7,
      "notes": "LIT0003",
      "recorded_by": "demo"
    },
    {
      "repro_id": 7,
      "ferret_id": 6,
      "event_type": "mated",
      "event_date": "2026-01-29",
      "partner_id": 7,
      "notes": "Sibling pairing (demo)",
      "recorded_by": "demo"
    },
    {
      "repro_id": 8,
      "ferret_id": 6,
      "event_type": "littered",
      "event_date": "2026-03-12",
      "partner_id": 7,
      "notes": "LIT0004",
      "recorded_by": "demo"
    },
    {
      "repro_id": 9,
      "ferret_id": 5,
      "event_type": "mated",
      "event_date": "2026-09-15",
      "partner_id": 2,
      "notes": "Open mating",
      "recorded_by": "demo"
    },
    {
      "repro_id": 10,
      "ferret_id": 4,
      "event_type": "estrus",
      "event_date": "2026-09-19",
      "partner_id": null,
      "notes": "In estrus",
      "recorded_by": "demo"
    },
    {
      "repro_id": 11,
      "ferret_id": 16,
      "event_type": "mated",
      "event_date": "2026-09-07",
      "partner_id": 2,
      "notes": "Died while mated",
      "recorded_by": "demo"
    }
  ],
  "death_records": [
    {
      "death_id": 1,
      "ferret_id": 1,
      "death_date": "2026-08-16",
      "cause_of_death": "Old Age",
      "cause_detail": "Age-related decline",
      "food_water_access": "yes",
      "cage_mates_present": "yes",
      "cage_mates_healthy": "yes",
      "recorded_at": "2026-08-16T12:00:00"
    },
    {
      "death_id": 2,
      "ferret_id": 16,
      "death_date": "2026-09-22",
      "cause_of_death": "Unknown",
      "cause_detail": "Found deceased in nest (demo)",
      "food_water_access": "yes",
      "cage_mates_present": "yes",
      "cage_mates_healthy": "unknown",
      "recorded_at": "2026-09-22T08:00:00"
    },
    {
      "death_id": 3,
      "ferret_id": 28,
      "death_date": "2026-05-07",
      "cause_of_death": "Unknown",
      "cause_detail": "Early kit death for 6-month survival demo",
      "food_water_access": "unknown",
      "cage_mates_present": "yes",
      "cage_mates_healthy": "yes",
      "recorded_at": "2026-05-07T12:00:00"
    }
  ],
  "death_notes": [
    {
      "note_id": 1,
      "death_id": 1,
      "note_type": "necropsy",
      "notes": "No acute findings. Consistent with old age.",
      "created_at": "2026-08-17T15:00:00",
      "created_by": "Riley Research",
      "performed_at": "2026-08-17",
      "performed_by": "Riley Research"
    },
    {
      "note_id": 2,
      "death_id": 2,
      "note_type": "general",
      "notes": "Died while listed as mated on the reproductive board.",
      "created_at": "2026-09-22T09:00:00",
      "created_by": "demo"
    }
  ],
  "death_photos": [],
  "research_studies": [
    {
      "study_id": 1,
      "study_name": "On-site behavior baseline",
      "description": "Baseline vs handling (demo).",
      "active": 1
    }
  ],
  "research_assignments": [
    {
      "assignment_id": 1,
      "study_id": 1,
      "ferret_id": 12,
      "cohort": "baseline",
      "assigned_date": "2026-08-31",
      "ended_at": null,
      "outcome": null
    }
  ],
  "distribution_events": [
    {
      "distribution_id": 1,
      "ferret_id": 15,
      "ferret_name": "Sable",
      "animal_id": 10015,
      "sex": "female",
      "distribution_date": "2026-09-05",
      "distributor_name": "North Lab Partners",
      "price": 0,
      "dist_notes": "Off-site research placement (demo).",
      "recorded_by": "demo"
    }
  ],
  "vet_communications": [
    {
      "comm_id": 1,
      "ferret_id": 6,
      "direction": "to_vet",
      "subject": "Weight plateau",
      "body": "Maple held weight this week. Please advise on diet.",
      "comm_date": "2026-09-17",
      "recorded_by": "demo"
    },
    {
      "comm_id": 2,
      "ferret_id": 6,
      "direction": "from_vet",
      "subject": "Re: Weight plateau",
      "body": "Continue current diet and reweigh in 7 days.",
      "comm_date": "2026-09-18",
      "recorded_by": "demo"
    }
  ],
  "exam_notes": [
    {
      "exam_note_id": 1,
      "ferret_id": 12,
      "exam_date": "2026-09-11",
      "notes": "Bright, alert. Assigned to behavior study.",
      "recorded_by": "Riley Research"
    }
  ],
  "location_history": [
    {
      "location_event_id": 1,
      "ferret_id": 1,
      "address_id": 8,
      "move_in": "2022-09-26",
      "move_out": null,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 2,
      "ferret_id": 2,
      "address_id": 5,
      "move_in": "2023-06-28",
      "move_out": null,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 3,
      "ferret_id": 3,
      "address_id": 6,
      "move_in": "2022-09-26",
      "move_out": null,
      "room_id": 3,
      "cage_address": "B",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 4,
      "ferret_id": 4,
      "address_id": 6,
      "move_in": "2023-08-27",
      "move_out": null,
      "room_id": 3,
      "cage_address": "B",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 5,
      "ferret_id": 5,
      "address_id": 5,
      "move_in": "2023-11-05",
      "move_out": null,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 6,
      "ferret_id": 6,
      "address_id": 3,
      "move_in": "2024-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 7,
      "ferret_id": 7,
      "address_id": 5,
      "move_in": "2024-03-12",
      "move_out": null,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 8,
      "ferret_id": 8,
      "address_id": 5,
      "move_in": "2024-05-20",
      "move_out": null,
      "room_id": 3,
      "cage_address": "A",
      "room_name": "Breeding",
      "room_lighting": "Bottom"
    },
    {
      "location_event_id": 9,
      "ferret_id": 9,
      "address_id": 1,
      "move_in": "2024-05-20",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 10,
      "ferret_id": 10,
      "address_id": 1,
      "move_in": "2024-07-01",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 11,
      "ferret_id": 11,
      "address_id": 2,
      "move_in": "2024-07-01",
      "move_out": null,
      "room_id": 1,
      "cage_address": "B",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 12,
      "ferret_id": 12,
      "address_id": 7,
      "move_in": "2024-07-01",
      "move_out": null,
      "room_id": 4,
      "cage_address": "A",
      "room_name": "Research",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 13,
      "ferret_id": 13,
      "address_id": 4,
      "move_in": "2025-08-21",
      "move_out": null,
      "room_id": 2,
      "cage_address": "B",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 14,
      "ferret_id": 14,
      "address_id": 4,
      "move_in": "2025-09-10",
      "move_out": null,
      "room_id": 2,
      "cage_address": "B",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 15,
      "ferret_id": 15,
      "address_id": 8,
      "move_in": "2025-05-13",
      "move_out": null,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 16,
      "ferret_id": 16,
      "address_id": 8,
      "move_in": "2025-01-13",
      "move_out": null,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 17,
      "ferret_id": 17,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 18,
      "ferret_id": 18,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 19,
      "ferret_id": 19,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 20,
      "ferret_id": 20,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 21,
      "ferret_id": 21,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 22,
      "ferret_id": 22,
      "address_id": 1,
      "move_in": "2026-08-14",
      "move_out": null,
      "room_id": 1,
      "cage_address": "A",
      "room_name": "Nursery",
      "room_lighting": "Top"
    },
    {
      "location_event_id": 23,
      "ferret_id": 23,
      "address_id": 3,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 24,
      "ferret_id": 24,
      "address_id": 3,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 25,
      "ferret_id": 25,
      "address_id": 3,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 26,
      "ferret_id": 26,
      "address_id": 3,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 27,
      "ferret_id": 27,
      "address_id": 3,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 2,
      "cage_address": "A",
      "room_name": "Grow-out",
      "room_lighting": "Middle"
    },
    {
      "location_event_id": 28,
      "ferret_id": 28,
      "address_id": 8,
      "move_in": "2026-03-12",
      "move_out": null,
      "room_id": 5,
      "cage_address": "A",
      "room_name": "Holding",
      "room_lighting": "Top"
    }
  ],
  "light_history": [
    {
      "id": 1,
      "ferret_id": 2,
      "start_date": "2026-07-27",
      "end_date": null,
      "eight_hour_light": 1,
      "recorded_by": "demo"
    }
  ],
  "activity_log": [
    {
      "log_id": 1,
      "user_id": 1,
      "username": "demo",
      "full_name": "Demo Admin",
      "action": "LOGIN",
      "table_name": "users",
      "record_id": 1,
      "details": "demo logged in",
      "created_at": "2026-09-25T08:00:00"
    },
    {
      "log_id": 2,
      "user_id": 1,
      "username": "demo",
      "full_name": "Demo Admin",
      "action": "CREATE_LITTER",
      "table_name": "litter_log",
      "record_id": 1,
      "details": "Recorded litter LIT0001 for Nova",
      "created_at": "2026-09-23T10:00:00"
    },
    {
      "log_id": 3,
      "user_id": 3,
      "username": "research",
      "full_name": "Riley Research",
      "action": "ASSIGN_RESEARCH",
      "table_name": "research_assignment",
      "record_id": 12,
      "details": "Assigned Reed to On-site behavior baseline",
      "created_at": "2026-08-31T11:00:00"
    }
  ],
  "care_schedule": {
    "weight_drop_pct": 10,
    "nail_interval_days": 30
  }
};
